### PR TITLE
migrate to null-safety

### PR DESCRIPTION
**Pull request by silverhairs**
## What?
Support for null-safety dart code.
## Why?
Because the package is not working in a project with null-safety.
## How?
- running `dart migrate` in both the package directory and the example project directory.
- allowing null for some variables.
## Anything Else?
The package is currently not working for projects that use dart 2.12.0 with null-safety enabled, It will be very helpful to upgrade it ASAP.

### CODE REVIEW

**Comment by job-46** [comment]
Hey,

May i ask why you changed every **IconData** to **IconData?** ?
`static const IconData? cubeOutline = const EvaIconData(0xea9d);`

These IconData's are filled in already so they can never be null right?

If have done it this way. Isn't this better since you don't have to check it again?: https://github.com/JobMoll/eva_icons_flutter

**Comment by silverhairs** [comment]
I just checked your code and you're totally right, sorry I just applied what dart suggested to me after I ran `dart migrate`, let me update the PR.

**Comment by job-46** [comment]
I am only not sure about 
**sdk: ">=2.12.0-0 <3.0.0"** what is the difference with **sdk: ">=2.12.0 <3.0.0"** isn't it just the same? I see it used through eachother.

**Comment by silverhairs** [comment]
*2.12.0-0* is from the dart dev channel [check here](https://dart.dev/get-dart) for more information.

**Comment by job-46** [comment]
So **sdk: ">=2.12.0-dev.68.0 <3.0.0"** can just be **sdk: ">=2.12.0 <3.0.0"** since null safety is on stable now?

**Comment by silverhairs** [comment]
Yes.

**Pull request merged**
